name: Test Build Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
